[tools]
hk = "latest"
pkl = "latest"
deno = "latest"

[tasks.prepare]
description = "Prepare for release (Run from GitHub Actions)"
run = """jq --arg v "{{option(name='version')}}" '.version = $v' deno.jsonc > tmp.json && mv tmp.json deno.jsonc"""

[tasks.publish]
description = "Publish to JSR (Run from GitHub Actions)"
run = "npx jsr publish"
