[template]
cargo_generate_version = ">= 0.23.0"
include = ["deno.jsonc", "LICENSE"]

[hooks]
init = ["../init.rhai"]
pre = ["../license.rhai"]

[placeholders.license]
type = "string"
prompt = "What license to use?"
choices = ["MIT"]
default = "MIT"
