[tools]
hk = "latest"
pkl = "latest"
"github:cargo-generate/cargo-generate" = "latest"

[settings]
experimental = true
npm.bun = true

[tasks.update-mod]
run = "find . -mindepth 2 -name cargo-generate-mod.rhai -exec cp cargo-generate-mod.rhai {} \\;"

[tasks.generate]
run = "cargo-generate generate --path ."
