name: Release
on:
  push:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      BASH_ENV: /tmp/bash_env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          github_token: ${{ github.token }}

      - name: Activate mise
        run: |
          # shellcheck disable=SC2016
          echo 'eval "$(mise activate bash)"' >> "$BASH_ENV"
          # shellcheck disable=SC1090
          . "$BASH_ENV"
          mise doctor

      - name: Run Checks
        run: hk check --all

      - name: Run Tests
        run: if mise task info test; then mise run test; fi

      - name: Semantic Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ github.token }}
