name: Build Template
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: test-project
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          github_token: ${{ github.token }}

      - name: Generate project
        run: mise exec github:cargo-generate/cargo-generate -- cargo-generate generate --path . --name "$PROJECT_NAME" --allow-commands base
        env:
          CARGO_GENERATE_VALUE_LICENSE: MIT

      - name: Run checks
        run: |
          cd "$PROJECT_NAME"
          hk check --all
